[package]
name = "image1"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = { version = "0.29", features = ["wgpu"] }
egui = "0.29"
image = { version = "0.25", features = ["jpeg", "png", "webp"] }
rfd = "0.15"